### PR TITLE
Sort albums chronologically in AlbumList on ArtistDetails

### PR DESCRIPTION
**Pull request by sentriz**
it makes sense to me. wdyt?

Screen Shot 2023-07-24 at 17 35 33
Screen Shot 2023-07-24 at 17 37 04

### CODE REVIEW

**Comment by tamland** [comment]
Hi. It should already be sorted (reverse) chronologically here: https://github.com/tamland/airsonic-refix/blob/master/src/shared/api.ts#L428

**Comment by sentriz** [comment]
@tamland ah i see. how would you feel about making it just chronological then?

**Comment by tamland** [comment]
I think most recent first makes :) But not opposed to adding a subtle toggle or some more customizability i principle. Just haven't had the time to do much of that yet

**Comment by sentriz** [comment]
ok fair, then maybe i will close in favour of #88 - that said i think i would prefer to be able to change sort order in the UI and keep the settings in localStorage instead of env vars

**Comment by tamland** [comment]
I have added a sorting toggle now:)

**Comment by sentriz** [comment]
it works very nice :+1: thanks!

**Pull request closed without merging**
