### PR TITLE
Add support for multiple album genres

### PR DESCRIPTION
**Pull request by sentriz**
in the same style as #115, but for album genres

[outw.webm](https://github.com/tamland/airsonic-refix/assets/6832539/b816725a-97ec-4114-87e4-04975368d7d9)

### CODE REVIEW

**Comment by sentriz** [comment]
good point, yes if we want to change to ids later it will be tricky. ill ask at @opensubsonic

**Comment by sentriz** [comment]
it looks like others are also thinking just string[] 

https://github.com/opensubsonic/open-subsonic-api/pull/51

i'd be inclined to agree too, since using genre ids would be a separate issue/proposal

**Comment by Tolriq** [comment]
Seeing this as a ref on the PR, there's no concept of genre ID in subsonic at all, so for the moment we have no choice. If there was an id it would be exposed here. I do not think that genre ID would bring much to the API so I kept the value as genres as there's nearly no chance we expose and ID later that would break this.

**Comment by Tolriq** [comment]
Well we can expose an array of genre that only have names for now but that's a bit strange and verbose.

If you can think of future needed properties in the future (I do not think Genre ID have a purpose as you can't have duplicate genre anyway) then I'm ok to change, but from all other provider and current experience I can't think of anything that should be exposed in those fields.
Any other fields would be exposed in the getGenres answers.

**Comment by tamland** [comment]
Genre IDs will allow name and possibly other properties to be changed without the actual identity changing. The same reason we use IDs for artist etc. Maybe when the server maps 1:1 what is in ID3 tags it won't make a difference, but in other scenarios it will.

Also genres currently require escaping by clients since they are sort of also IDs and needs to be passes back to the server (see getAlbumList2)

**Comment by Tolriq** [comment]
Ok well then make an API Request on OpenSubsonic to add support for Genre ID, I'll update the genre field to return genre objects without IDs for now to allow that future change.

**Comment by sentriz** [comment]
@tamland updated as per https://github.com/opensubsonic/open-subsonic-api/pull/51#issuecomment-1739860198 :+1:

**Pull request merged**
