### PR TITLE
Add build to the Docker container

### PR DESCRIPTION
**Pull request by archekb**
Add build to the Docker container

### CODE REVIEW

**Comment by sentriz** [comment]
:+1: :+1: 

i've had the same change locally for ages 
image

**Comment by archekb** [comment]
Yes it's very helpful. You do not need setup environment for building last version on the server.

**Comment by tamland** [comment]
Wondering if this breaks build version/date embedding? The app is already built by CI and passed on to the docker build stage: https://github.com/tamland/airsonic-refix/blob/67bba86ad74fe4485dff3f201ede8dab403ffefb/.github/workflows/ci.yml#L15-L32

**Comment by archekb** [comment]
I was add arg `VERSION` for builder container. Now it should works correctly. And for manual buildings too.

**Pull request closed without merging**
